
package org.etsi.uri.ts102204.etsi204_kiuru_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-23T11:52:20.581+01:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "Fault", targetNamespace = "http://www.w3.org/2003/05/soap-envelope")
public class MSSFaultMessage extends Exception {

    private org.w3._2003._05.soap_envelope.Fault fault;

    public MSSFaultMessage() {
        super();
    }

    public MSSFaultMessage(String message) {
        super(message);
    }

    public MSSFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MSSFaultMessage(String message, org.w3._2003._05.soap_envelope.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public MSSFaultMessage(String message, org.w3._2003._05.soap_envelope.Fault fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.w3._2003._05.soap_envelope.Fault getFaultInfo() {
        return this.fault;
    }
}
